Search in DOM , task5
mishalfirdous/talentpool pull request #8
Opened 2023-12-05 09:44 UTC by mishalfirdous

2023-12-05 12:15 UTC, mustaqeemtariq requested changes
Kindly see the comments. Thanks

2023-12-05 12:15 UTC, mustaqeemtariq commented on edit portfolio.html
>      </header>
We don't need this extra div inside header. We can directly apply navbar class to the header. Also it would make more sense to update the class name to header or change the tag to nav instead of header for navbar.

2023-12-05 12:15 UTC, mustaqeemtariq commented on edit portfolio.html
>              <input
You should use proper form tag to create a form and attach onSubmitEventListener to it in order to create a new experience. Please update this.

2023-12-05 12:15 UTC, mustaqeemtariq commented on javascript.js
> +    );
It is mentioned in the task that edit and delete button should be on the top right of each entry so kindly update that.

2023-12-05 12:15 UTC, mustaqeemtariq commented on javascript.js
> +    );
I think that when using form you already get the form data in onSubmit funtion so why are we using onClick here as well. Can you kindly explain this?

2023-12-05 12:15 UTC, mustaqeemtariq commented on javascript.js
> +}
Why are we checking for index !== -1 here. When a user deletes an entry won't it always be present beforehand?

2023-12-05 12:15 UTC, mustaqeemtariq commented on javascript.js
> +      entry.style.display = "block"; // Show if matches the search criteria
What is this querySelector("strong"). Can you use better naming here please.

2023-12-07 06:20 UTC, mishalfirdous commented on edit portfolio.html
>      </header>
resolved!

2023-12-07 06:46 UTC, mishalfirdous commented on javascript.js
> +      entry.style.display = "block"; // Show if matches the search criteria
resolved!

2023-12-07 07:07 UTC, mishalfirdous commented on javascript.js
> +}
resolved!

2023-12-07 07:15 UTC, mishalfirdous commented on javascript.js
> +    );
I have changed, fixed!

2023-12-07 10:31 UTC, mishalfirdous commented on javascript.js
> +    );
resolved!

2023-12-11 07:06 UTC, mishalfirdous commented on edit portfolio.html
>              <input
fixed!

2023-12-11 08:03 UTC, mustaqeemtariq approved these changes
Looks good to me.

2023-12-13 06:34 UTC, merged